# fly.toml app configuration file generated for kierkegaard-bot on 2026-01-13T15:25:08+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'kierkegaard-bot'
primary_region = 'ams'

[build]
  dockerfile = 'Dockerfile'

[env]
  JAVA_OPTS = '-Xmx256m'

[[mounts]]
  source = 'quotes_data'
  destination = '/app/data'

[[vm]]
  memory = '1gb'
  cpus = 1
  memory_mb = 1024
